version: '3.1'
services:
  gateway_web:
    image: "node:lts"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8080"
    command: "npm start"
    ports:
      - 8080:8080
    networks:
      - gateway

networks:
  gateway:
    external:
      name: gateway
